### ISSUE TITLE
How to run the tests using the "compile" command?

### ISSUE THREAD

**Issue by taniodev** [wbolster/emacs-python-pytest#50]
Hi, congratulations on the great work done on this project!

I would really like to be able to run the tests through the Emacs compilation framework, it would give me the power to use "compile", "recompile" and "kill-compilation".
Is there any way to configure this package to do this?

Thanks!

**Comment by wbolster** [comment]
it is too long ago for me to remember the exact details, but o ended up using comint-mode (interactive compilation mode) because it solved a variety of problems, iirc things like pdb (debugger) shells with command history etc.

assuming you use shortcuts for the commands you mentioned, you may be able to rebind those to the equivalent commands (python-pytest-repeat etc) in both python-mode and python-pytest-mode buffers.
